task:
  name: tinystories
  output_dir_name: tinystories
  batch_size: 128
  max_epochs: 50
  max_steps: null
  samples_per_epoch: # how many blocks to sample per epoch
    train: 100_000    # at most (473,992,006 - block_size - 1)
    val: 5000        # at most (4,765,918 - block_size - 1)
    test: 500_000     # at most (4,765,918 - block_size - 1)
  target_metric: val_perplexity
  target_metric_mode: min
  model:
    n_layer: 8
    n_head: 8
    n_embd: 128
    block_size: 256
    dropout: 0.2
    bias: true
engine:
  devices: 1
  sbatch_args:
    time: 01:30:00
optimizer:
  name: adamw_baseline
  learning_rate: 1.e-3
  beta2: 0.99
  lr_scheduler:
    eta_min_factor: 0.1
evaluation:
  plot:
    metric: test_perplexity
    test_metric_mode: min
    format: "0.2"
    limits: [0, 10]
