optimizer:
  name: adamcpr
  learning_rate: 1.e-3
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.e-8
  kappa_init_param: 1.0
  kappa_init_method: warm_start_factor
  reg_function: l2
  kappa_update: 1.0
  foreach: null
  regularize_all: false
  adacpr_method: disable
  reduce_kappa: false
